# -*- coding: utf-8 -*-
"""ASSET.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ii4lLtMYIGeHNhHHIEO0WTbRJb_cKTp0
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
#import seaborn as sns
#import matplotlib.pyplot as plt

# %matplotlib inline



import yfinance as yf

msft = yf.Ticker("MSFT")

#msft.info

hist = msft.history(period="1y")
hist

msft.institutional_holders

msft.recommendations

msft.recommendations['To Grade'].value_counts()

msft.calendar

#international security identification code
msft.isin

hist.plot(kind="line", figsize=(12,12), subplots=True)

